// <auto-generated />
namespace Tarea1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddNullablePropertyToFechaSalidaInRegistroGuardia : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201209030247146_AddNullablePropertyToFechaSalidaInRegistroGuardia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN1a227jNhB9L9B/EPTUFljLm6KL3YWzi9RJFkGbC+J0Xxe0NHaIUqRKUoH9bX3oJ/UXOpItiRJ19SW76UsQU+ThcHhmODrUv3//M/m4CpnzBFJRwU/d16Ox6wD3RUD58tSN9eLVW/fjh++/m1wE4cr5nPU7SfrhSK5O3Ueto/eep/xHCIkahdSXQomFHvki9EggvJPx+K33euwBQriI5TiT+5hrGkL6A39OBfch0jFh1yIAprbt+GSWojo3JAQVER9O3QcigbwebTq6zhmjBI2YAVsMtGj8LrHIzefC2S7QKr1+WEeQznjqXnENS0nwr9kPe/4G61IDNt1JEYHU63tYWKOvAtfxygheFSIHqB2dGJW2/XziOjcxY2TOsGFBmALXid68n2kh4RNwkERDcEe0Bok7dRVAuqitc95Hb/r55503Pkn84xHOhSYat91aQsXgGxHOJWSmzrREDrnOJV1B8DvwpX7Mzb0mq6wF/3WdPzhFyuEgLWOoWV77vGcRMEYD8fwz38f6+SedErkU3ZSogNyQJ7pMt7EOznXugaVP1SONNuE0Sp98KWiI0XYpRXgvWDbMfPgFA3MJiT9EU4+ZiKU/wLR7WFKlpfgUExlgmNdaWelkTGia29zLsrula90CJl6RNVpzycbRO6SRfMOHZpCeTPkmkscD1TH7CiF8J6mQNCAHi6dSvOwfVRnlmqMq4+9OpKyQfRd6ViB2IWoNxAug7JADuh3pEvxHcsWXElQeAue4rAeskXYDmxE8EUkb1iZahrP6OEm4SvMe+boP38+UEj5NrTVzYin8yh644IHTGYubHJVHM+akmGkaMeqjDVhFu9WoueXnwECDc+brtICeEuWTwN4AXEfQ36D86CoMMj1ftuonazKMYZBJuBCGFTi6m1Cu7YCn3KcRYV1uqQwccpQlC8/nqT45hwh4EtVdbtjTgHyeyo50eWniGSxrJ19LmDRtep+YKXa/ms47KdBr"
                       + "okE0Oyj5d2Jo90r6MKXt5W0QX7t38BDmHJy9m4SKYzSOAJmVaenb9/k8aYeVtmibjJmBrquFigxdwyGLlmWgNGzrMLb5t2O4/SJhAVmRU4E0vFQxq1zLGf0aC77q5vU5c/IlFc6wSNDnqDBwSnZXQ7G83h6+aCsBbKf0zYRDc6GxPHvTWxzWI/vt7bmsSMljqpC5vI3OlelhXoMgNrkmUYQvRoZAtm1xZht1bPpqNlwGCzcYnq9q1LDc2nwmLLzJEipPcWq09JJKpbHaJHOSFKrTILS69cwg2Wx2IrE3MQvlbEzyv5mutmLhqJlkhSMvcW1hkrzT94vaPbcHp0IlYUS2viFMBYtD3iedNyNmGpuJlbX1RykUMxOnaO2PlCpgJkja0H98Xo+ZGI1FWhIalX2yDkKLDlaNUWZYL/5tU+7u1KsRf1KELtY1jDuUO5twMjXGhMna+qMY2ooJZDR/MxtsHRa7b3WrpNJr0zsRGqPR1lFKsdml1LRhHz6XlVUPE7H8ZCBiJn1YgNmDZyaddexXu+Sz58d/5ZifbI/c7ssx6wzedHEddNQTDZLzd7ZWGsJR0mE0+4tNGcX1Fh2uCacLUPpB/AnJRd94/Mvul2y5qKZUwF7WTRtNnNKpMQ6U5so3ZPyJSKSl/CEkqx/3vvXaD824ydoPqHLnkLqxFeLl3J8chRLle4/9fG/dZRzQ+9/4RcFR9qYxLxxA3g/QRH0geb8Oy5b3j6aRfzVB3JQYnl0Cfza9u/Wt9X+gcA/exSOxyVIA99HVd+LVwJ0+lkL9kvRoW3Tqq0h3CNKbwhlz6zzJb5uc2ib71SrWzYJ1HXz6qAe0RcZuMbtuui599Dklb1vfblVr7V2sSnQvQs8evIz2fNWiIBxFpLbfSjG8jQ87Mc8ouiwgks88OfilwM77XPGFyLJMxaKsS6UQugZNsPIhZ1LTBfE1PvZBqfS7oc+ExdjlIpxDcMVvYx3FGpcM4ZytTWckeapt/lSJ"
                       + "L9s8uY3Sjx8OsYTPaRmn4Zb/GlMW5HZf1hTqDRBJAtyWvMle6qT0Xa5zpBvBewJt3Zfn7QcII4Zg6pbPyBM029btw7LHJueUIL1DtcUoxuNPpF8Qrj78B5ps9XOaLAAA"; }
        }
    }
}
