// <auto-generated />
namespace Tarea1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class NoTengoIdeaQueMigre : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201209030016502_NoTengoIdeaQueMigre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN1a227jNhB9L9B/EPTUFljLm6KL3YWzi9RJFkGbC+J0Xxe0NHaIUqRKUYH9bX3oJ/UXOpItiRJ1oXzJbvoSxBR5OByeGY4O9e/f/0w+rkLmPIGMqeCn7uvR2HWA+yKgfHnqJmrx6q378cP3300ugnDlfM77naT9cCSPT91HpaL3nhf7jxCSeBRSX4pYLNTIF6FHAuGdjMdvvddjDxDCRSzHmdwnXNEQsh/4cyq4D5FKCLsWAbB4245PZhmqc0NCiCPiw6n7QCSQ16NNR9c5Y5SgETNgi4EWjd+lFrnFXDjbBVql1g/rCLIZT90rrmApCf7V+2HP32BdacCmOykikGp9Dwtj9FXgOl4VwatDFACNo1OjsrafT1znJmGMzBk2LAiLwXWiN+9nSkj4BBwkURDcEaVA4k5dBZAtauuc99EbO/+888YnqX88wrlQROG2G0uoGXwjwrmE3NSZksgh17mkKwh+B75Uj4W512SVt+C/rvMHp0g5HKRkAg3L6573LALGaCCef+b7RD3/pFMil6KfEjWQG/JEl9k2NsG5zj2w7Gn8SKNNOI2yJ19KGmK0XUoR3guWD9MffsHAXELqD9HWYyYS6Q8w7R6WNFZSfEqIDDDMG62sddIm1M1t72XY3dG1aQETr8wanblk4+gd0kix4UMziCVTvonk8UBVwr5CCN9JKiQNyMHiqRIv+0dVTrn2qMr5uxMpa2TfhZ41iF2I2gDxAig75IDuRroE/5Fc8aWEuAiBc1zWA9ZIu4HNCJ6IZDiWBa2Pk4XrPLdI2DaEP4tj4dPMWj0pVuKv6oELHji9wbhJUkU4Y1JKmKIRoz7agGW0Ww+bW34ODBQ4Z77KKugpiX0SmBuA6wjsDSrOrtIg3fNVq34yJsMgBpnGC2FYgqO7CeXKjHjKfRoR1ueW2sAhZ1m68GKe+pNziICnYd3nhj0NKOap7UiflyaexrJu8nWESdum28RMufv1fN5LAauJ"
                       + "BtHsoOTfiaH9K7FhStfb2yC+9u/gIcw5OHs3CRXHKBwBMq/Tstfv83naDitl0DYdMwPVVAyVGbqBQwYtq0BZ2DZhbPNvz3DzTcIAMiKnBql5qWZWtZjT+rVWfPXNszlziiWVzjBIYHNUaDgVu+uhWF2vhS+6SgDTKbaZcGgu1JZnbnqHwyyy396ey4uUIqZKncvbCF25IOa1KGKTaxJF+GakKWTbFme2kcemr2bDdbBwg+H5cYMcVlhbzISVN1lC7SlOjZZeUhkrLDfJnKTV5TQIjW6WGSSfzUwk5ibmoZyPSf/X09VWLRy1k6x05CWuLUyTd/aC0bjn5uBMqSSMyM5XhKlgScht0nk7Yi6y6Vh5mz1KKZnpOGWrPVImgekgWYP9+KIe0zFai7Q0NGr7ZByEBh2MGqPKMCv+bVPu7tRrUH8yhD7WtYw7lDvbcHI5RofJ2+xRNHFFB9Kav5kNNg6L3be6U1Ox2vRehNZoNIWUSmz2STVd2IfPZVXZQ0esPhmImGsfBmD+4JlJZxz79S7F7MXxXzvmJ9sjt/92zDiDN11cBx31RIP0/J2tYwXhKO0wmv3FpoziessO14TTBcTqQfwJ6U3fePzL7rdshaoWxwF7WVdtNHVKr8g4UJurXpHxJyKRlvKHkKx+3Pvaaz807SprP6DapUPmxk6Il3OBchRKVC8+9vO9cZlxQO9/4zcFR9mb1rxwAH0/QBPVgfR9S6yjieRfTRHXNYZn18CfTfDufG39H0jcg3fxSGwyJMB9hPWdeDVwp48lUb8kQdpUnWwl6R5FelM5Y3Kdp/ltk1S7dL9GybpdsW6Czx5ZQBtk7Fezm6brE0ifU/M2Be5OudbcxbpG9yIE7cHL6M5XHRLCUVRq87UUw1v7tBPzTEyXJUT6oScHvxLYRZ8rvhB5lqlZlHepVULXoAiWPuRMKrogvsLHPsRx9uXQZ8IS7HIRziG44reJihKFS4Zwzta6M9I81TV/JsVXbZ7c"
                       + "RtnXD4dYwuesjlNwy39NKAsKuy8bqrcWiDQBbmvedC9VWvsu1wXSjeCWQFv3FXn7AcKIIVh8y2fkCdpt6/dh1WOTc0qQ3mG8xSjH40+kXxCuPvwHWqXxdJwsAAA="; }
        }
    }
}
